### ISSUE TITLE
Issue with saved excitation field amplitudes when saving single particle data

### ISSUE THREAD

**Issue by TobiasKlemme** [Neumann-A/StochasticPhysics#15]
Saved excitation fields are not equal for different particles, when "Save_single_simulations" is enabled and there are less Number_of_simulators then Number_of_simulations

[Field_Issue_cfg_files.zip](https://github.com/Neumann-A/StochasticPhysics/files/9912623/Field_Issue_cfg_files.zip)

**Comment by Neumann-A** [comment]
Fixed with 6c8074a994c079064d3220ae389465122cf96c2f. Only the field stored for single simulations were affected and only if there are no further simulators queued and running.
